#!/usr/bin/env python

env = SConscript("godot-cpp/SConstruct")

lib_name = "shogi_engine"

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "../bin/{}.{}.{}.framework/{}".format(lib_name, env["platform"], env["target"], lib_name),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "../bin/{}{}{}".format(lib_name, env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

env.NoCache(library)
Default(library)
