#!/usr/bin/env python

env = Environment(tools=["default"], PLATFORM="", compiledb_file="build/compile_commands.json")
env = SConscript("godot-cpp/SConstruct", {"env": env})

lib_name = "shogi_engine"

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "../bin/{}.{}.{}.framework/{}".format(
            lib_name, env["platform"], env["target"], lib_name
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "../bin/{}{}{}".format(lib_name, env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

if env["platform"] == "windows":
    test_env = env.Clone()
    test_env.Replace(CPPPATH=["#src"], LIBS=[], LIBPATH=[])
    test_env.VariantDir("build/test/src", "src", duplicate=0)
    test_env.VariantDir("build/test/test", "test", duplicate=0)
    test_sources = [
        f for f in Glob("build/test/src/*.cpp")
        if f.name not in ("shogi_engine.cpp", "register_types.cpp")
    ] + Glob("build/test/test/*.cpp")
    test_program = test_env.Program("build/test/shogi_tests", test_sources)
    test_run = test_env.Command(
        "build/test/run",
        [test_program, File("../assets/data/zobrist_params.bin")],
        '"${SOURCES[0].abspath}" "${SOURCES[1].abspath}"',
    )
    test_env.AlwaysBuild(test_run)
    Alias("tests", test_run)

if env["platform"] != "web":
    Default("compiledb")

env.NoCache(library)
Default(library)
